<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <AssemblyName>ZipZip.ShellExtension</AssemblyName>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZipZip.Application\ZipZip.Application.csproj" />
    <ProjectReference Include="..\ZipZip.ArchiveAdapters\ZipZip.ArchiveAdapters.csproj" />
    <ProjectReference Include="..\ZipZip.Domain\ZipZip.Domain.csproj" />
  </ItemGroup>
</Project>
